services:
  - type: static
    name: e-learning-client
    branch: main
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        value: https://e-server-9hky.onrender.com # You'll need to replace this with your actual backend URL
    headers:
      - source: /*
        headers:
          - key: Cache-Control
            value: public, max-age=0, must-revalidate
