services:
  - type: web
    name: e-learning-client
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://your-backend-url.onrender.com # You'll need to replace this with your actual backend URL
